export {default as TextInput} from './TextInput'
export {default as PraymaryButton} from './PraymaryButton'
export {default as ComentCard} from './ComentCard'
export {default as MiniSpecer} from './MiniSpecer'
export {default as ImageArea} from './ImageArea'